[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solquest_contract = "C1q7Wna7sMz5CyJmzGhshdsbjEa2ULHEqTpk6gfQYE8x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
